version: '3.8'

services:
  weblumar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weblumar
    ports:
      - "1010:8080"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - weblumar_network

networks:
  weblumar_network:
    driver: bridge 